#!/bin/bash

echo "=== Jenkins Setup Guide ==="
echo ""
echo "1. Open Jenkins at: http://localhost:8080"
echo "2. Use initial password: e57f66eecec74696be78217fbfef85e7"
echo "3. Install suggested plugins"
echo "4. Create admin user"
echo ""
echo "=== Required Plugin Installation ==="
echo "Go to Manage Jenkins > Manage Plugins > Available and install:"
echo "- Git plugin"
echo "- GitHub plugin"
echo "- Pipeline plugin"
echo "- NodeJS plugin"
echo "- Maven Integration plugin"
echo "- HTML Publisher plugin"
echo "- Test Results Analyzer"
echo ""
echo "=== Global Tool Configuration ==="
echo "Go to Manage Jenkins > Global Tool Configuration and configure:"
echo ""
echo "Maven:"
echo "  Name: Maven-3.9.10"
echo "  MAVEN_HOME: $(which mvn | sed 's|/bin/mvn||')"
echo ""
echo "NodeJS:"
echo "  Name: NodeJS-18"
echo "  Installation directory: $(which node | sed 's|/bin/node||')"
echo ""
echo "Git:"
echo "  Name: Default"
echo "  Path to Git executable: $(which git)"
echo ""
echo "=== Create Pipeline Job ==="
echo "1. New Item > Pipeline"
echo "2. Name: 'SG-Kata-Pipeline'"
echo "3. Pipeline section:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: [Your GitHub repo URL]"
echo "   - Credentials: [Add your GitHub credentials]"
echo "   - Branch: */main"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "=== GitHub Integration ==="
echo "1. In your GitHub repo, go to Settings > Webhooks"
echo "2. Add webhook: http://your-jenkins-url:8080/github-webhook/"
echo "3. Content type: application/json"
echo "4. Events: Just the push event"
echo ""
echo "Current paths:"
echo "Maven: $(which mvn)"
echo "Node: $(which node)"
echo "Git: $(which git)"
echo "Java Home: $JAVA_HOME"
